spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_paper_db
    username: order_manager
    password: order!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false

server:
  port: 8080